# Generated by Django 5.0.6 on 2024-07-08 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, 
                                           primary_key=True, serialize=False, 
                                           verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, 
                                           primary_key=True,
                                           serialize=False, 
                                           verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, 
                                           primary_key=True,
                                           serialize=False, 
                                           verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, 
                                           primary_key=True,
                                           serialize=False, 
                                           verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, 
                                           primary_key=True,
                                           serialize=False, 
                                           verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, 
                                                 primary_key=True,
                                                 serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MedicationInfo',
            fields=[
                ('medication_id', models.AutoField(primary_key=True, 
                                                   serialize=False)),
                ('dosage', models.CharField(max_length=8)),
                ('medication_time', models.JSONField()),
                ('misc_information', models.CharField(blank=True, 
                                                      max_length=200, 
                                                      null=True)),
                ('frequency', models.CharField(blank=True, max_length=20, 
                                               null=True)),
                ('medication_name', models.CharField(blank=True, 
                                                     max_length=30, 
                                                     null=True)),
                ('active_medication', models.BooleanField(blank=True, 
                                                          null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'medication_info',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, 
                                             serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(max_length=50)),
                ('password_hash', models.CharField(max_length=25)),
                ('phone_number', models.TextField(blank=True, null=True)),
                ('birthday', models.DateField()),
                ('blood_type', models.CharField(blank=True, max_length=2, 
                                                null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SymptomLog',
            fields=[
                ('symptom_id', models.AutoField(primary_key=True, 
                                                serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('description', models.CharField(max_length=200)),
                ('severity', models.CharField(blank=True, max_length=20, 
                                              null=True)),
                ('user', models.ForeignKey(blank=True, null=True, 
                                           on_delete=django.db.models
                                           .deletion.DO_NOTHING, 
                                           to='api.users')),
            ],
            options={
                'db_table': 'symptom_log',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Refills',
            fields=[
                ('refill_id', models.AutoField(primary_key=True, 
                                               serialize=False)),
                ('active', models.BooleanField(blank=True, null=True)),
                ('refill_date', models.CharField(blank=True, 
                                                 max_length=10, null=True)),
                ('refill_time', models.TimeField(blank=True, null=True)),
                ('num_meds', models.IntegerField(blank=True, null=True)),
                ('medication', models.ForeignKey(blank=True, null=True, 
                                                 on_delete=django.db.models
                                                 .deletion.DO_NOTHING, 
                                                 to='api.medicationinfo')),
                ('user', models.ForeignKey(blank=True, null=True, 
                                           on_delete=django.db.models
                                           .deletion.DO_NOTHING, 
                                           to='api.users')),
            ],
            options={
                'db_table': 'refills',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='medicationinfo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db
                                    .models.deletion.DO_NOTHING, 
                                    to='api.users'),
        ),
        migrations.CreateModel(
            name='MedicationLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, 
                                            serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('taken', models.BooleanField(blank=True, null=True)),
                ('colour', models.CharField(blank=True, 
                                            max_length=20, 
                                            null=True)),
                ('medication', models.ForeignKey(blank=True, null=True, 
                                                 on_delete=django.db.models
                                                 .deletion.DO_NOTHING, 
                                                 to='api.medicationinfo')),
                ('user', models.ForeignKey(blank=True, null=True, 
                                           on_delete=django.db.models
                                           .deletion.DO_NOTHING, 
                                           to='api.users')),
            ],
            options={
                'db_table': 'medication_log',
                'managed': True,
                'unique_together': {('medication', 'user', 'date')},
            },
        ),
    ]
