name: medication_reminder_app

environment:
  sdk: '>=3.2.2 <4.0.0'
  
dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  flutter_test:
    sdk: flutter
  http: ^1.2.1
dev_dependencies:
  flutter_lints: ^4.0.0

