#!/bin/bash

export FILTER_BRANCH_SQUELCH_WARNING=1 # This will suppress the warning shown by git

git filter-branch -f --env-filter '
    if test "$GIT_AUTHOR_NAME" = "group117"
    then
        GIT_AUTHOR_NAME="SylvieAsija"
        GIT_AUTHOR_EMAIL=19aa10@queensu.ca
    fi
    if test "$GIT_COMMITTER_NAME" = "group117"
    then
        GIT_COMMITTER_NAME="SylvieAsija"
        GIT_COMMITTER_EMAIL=19aa10@queensu.ca
    fi
' HEAD
