name: Flutter Lint

on:
  push:
    paths:
      - 'frontend/**'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'
          
      - name: Verify Flutter Installation
        run: flutter --version

      - name: Install dependencies
        run: |
          cd frontend/lib
          flutter pub get

      - name: Run analyzer
        run: |
          cd frontend/lib
          flutter analyze
